### ISSUE TITLE
Problem time playing

### ISSUE THREAD

**Issue by marva2013** [VideoExpertsGroup/MediaPlayerSDK#10]
I have a problem with streaming video : the video will be stoped after 2 minutes how can i resolve this problem. Thanks.

**Comment by VideoExpertsGroup1** [comment]
Hello,
This is the Evaluation version of VXG Mobile Video Player SDK - https://www.videoexpertsgroup.com/vxg-video-sdk/
If you would like to purchase the licensed version without limitation please contact us - expert@videoexpertsgroup.com

Best regards,
VXG Team
