### ISSUE TITLE
i use the new android sdk,why the playcallback reponse "CP_ERROR_DISCONNECTED" about 2min. becase a trail version ?

### ISSUE THREAD

**Issue by welcomeem** [VideoExpertsGroup/MediaPlayerSDK#14]
i use the new android sdk,why the playcallback reponse "CP_ERROR_DISCONNECTED" about 2min. a trail version ? tks for you answer.

**Comment by VideoExpertsGroup1** [comment]
Hello,

Yes, it is a trial version with playback time limitation.

Best regards,
VXG Team
