### ISSUE TITLE
MediaPlayerSDKTest_StreamControl demo is crashing

### ISSUE THREAD

**Issue by MhtSuthar** [VideoExpertsGroup/MediaPlayerSDK#5]
Hi, I tried to run MediaPlayerSDKTest_StreamControl demo to run RTSP link on Android MarshMallow device (Moto G). But it is not working and crashing. Please find below error.

` E/art: No implementation found for int veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(int[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3ILveg_mediaplayer_sdk_MediaPlayer_2)
06-29 17:51:21.966 6269-7033/veg.mediaplayer.sdk.teststreamcontrol E/AndroidRuntime: FATAL EXCEPTION: MediaPlayerThread
                                                                                     Process: veg.mediaplayer.sdk.teststreamcontrol, PID: 6269
                                                                                     java.lang.UnsatisfiedLinkError: No implementation found for int veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(int[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3ILveg_mediaplayer_sdk_MediaPlayer_2)
                                                                                         at veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(Native Method)
                                                                                         at veg.mediaplayer.sdk.MediaPlayerWorker.run(MediaPlayer.java:3338)
                                                                                         at java.lang.Thread.run(Thread.java:818)`

Please let me know any suggestion for this.

Thanks.

**Comment by toby11** [comment]
I have this same issue, is there any update on why it happens?

This is on a Galaxy S7 Edge

08-08 09:39:06.485 7711-8711/xxxl E/AndroidRuntime: FATAL EXCEPTION: MediaPlayerThread
                                                                                Process: xxx, PID: 7711
                                                                                java.lang.UnsatisfiedLinkError: No implementation found for int veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(int[], veg.mediaplayer.sdk.MediaPlayer) (tried Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit and Java_veg_mediaplayer_sdk_MediaPlayer_nativePlayerInit___3ILveg_mediaplayer_sdk_MediaPlayer_2)
                                                                                    at veg.mediaplayer.sdk.MediaPlayer.nativePlayerInit(Native Method)
                                                                                    at veg.mediaplayer.sdk.MediaPlayerWorker.run(MediaPlayer.java:3338)
                                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by VideoExpertsGroup1** [comment]
Hi Toby,

Please try this step-by-step guide:
https://www.dropbox.com/s/krsr6f5pbr3hvui/20160502_Release_AndroidStudioProjects_MediaPlayerSDKTest.pdf?dl=0

Regards,
VXG Team

**Comment by toby11** [comment]
thanks all working now!

Toby

**Comment by prasadaraobankuru** [comment]
No implementation found for int veg.mediaplayer.sdk.Thumbnailer.nativeThumbnailerInit(veg.mediaplayer.sdk.Thumbnailer) (tried Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit and Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit__Lveg_mediaplayer_sdk_Thumbnailer_2)
                                                            

please help me i am getting this error

**Comment by elluminati10** [comment]
FATAL EXCEPTION: ThumbnailerThread
Process: org.rtspplayer.sample, PID: 22694
java.lang.UnsatisfiedLinkError: No implementation found for int veg.mediaplayer.sdk.Thumbnailer.nativeThumbnailerInit(veg.mediaplayer.sdk.Thumbnailer) (tried Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit and Java_veg_mediaplayer_sdk_Thumbnailer_nativeThumbnailerInit__Lveg_mediaplayer_sdk_Thumbnailer_2)
at veg.mediaplayer.sdk.Thumbnailer.nativeThumbnailerInit(Native Method)

I get this error when I add other files in folder jniLibs. I am using OpenCV and I need to keep files in jniLibs folder along with files related to mediaplayer SDK. When I remove other files from jniLibs, it does not crash, but if I keep those files in jniLibs it crashes with above error only in Lolipop and not on other version.

**Comment by shellyb985** [comment]
@elluminati10 Somehow it works now. Thanks!
