### ISSUE TITLE
Deprecated OpenSSL Issue in MediaplayerSDK Library

### ISSUE THREAD

**Issue by hb-abhishek** [VideoExpertsGroup/MediaPlayerSDK#8]
Hello Video Experts Group Team,

We have used MediaPlayerSDK for our RTSP player Android application. The application is already live on Google Play store.

But due to Google Play store policy change it is not accepting any updates of that application. They are giving following link as a reason for the rejection.
https://support.google.com/faqs/answer/6376725?hl=en-GB

After using the command **$ unzip -p YourApp.apk | strings | grep "OpenSSL"** I found that MediaPlayerSDK and its .so files uses old version of OpenSSL.

Can you please look into the issue?

**Comment by VideoExpertsGroup1** [comment]
Hello!

Have you purchased our license? Please tell us your package name in the email to expert@videoexpertsgroup.com

Best regards,
VXG Team
