### ISSUE TITLE
Not able to stream video in android lolipop

### ISSUE THREAD

**Issue by naveen1988** [VideoExpertsGroup/MediaPlayerSDK#9]
Hi
I have integrated mediaplayer sdk into my application to stream RTSP data. My app works fine in kitkat version but not in lollipop n marshmallow. Below is the error i am getting when i stream IP camera.
Please do needful

10-05 15:28:41.447    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Start closing...
10-05 15:28:41.447    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Start closing no due: null,false
10-05 15:28:41.447    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Thread started
10-05 15:28:41.449    9118-9562/com.ims.mid.android.sahamonitor.newui E/Test﹕ nativeInit
10-05 15:28:41.449    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ onStart()
10-05 15:28:41.449    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ onResume()
10-05 15:28:41.451    9118-9562/com.ims.mid.android.sahamonitor.newui I/SDL﹕ SDL_Android_Init()
10-05 15:28:41.451    9118-9562/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Android_JNI_SetupThread
10-05 15:28:41.451    9118-9562/com.ims.mid.android.sahamonitor.newui I/SDL﹕ SDL_Android_Init() finished!
10-05 15:28:41.457    9118-9562/com.ims.mid.android.sahamonitor.newui E/MediaPlayerTest﹕ Form Native Player status: 101
10-05 15:28:41.459    9118-9563/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Android_JNI_SetupThread
10-05 15:28:41.459    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/content_provider_thread.c﹕ AttachCurrentThread : 0
10-05 15:28:41.459    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/content_provider_thread.c﹕ Content provider init: 1
10-05 15:28:41.459    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/content_provider_thread.c﹕ Content provider open: 1
10-05 15:28:41.470    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/file_content_provider.c﹕ file_cp_open: urls: rtsp://119.81.67.138:2950/157944612fae1a.mp4, rtsp_transport: http, datareceive 30000000
10-05 15:28:41.470    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/file_content_provider.c﹕ file_cp_open: try url: rtsp://119.81.67.138:2950/157944612fae1a.mp4, rtsp_transport: http
10-05 15:28:41.511    9118-9118/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ export_player_get_aspect_ratio_sizes1: 1, 0, 0, 720, 1038
10-05 15:28:41.511    9118-9118/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ export_player_get_aspect_ratio_sizes2: 1, 0, 0, 720, 1038
10-05 15:28:41.534    9118-9118/com.ims.mid.android.sahamonitor.newui I/System.out﹕ player error2 :
10-05 15:28:41.566    9118-9118/com.ims.mid.android.sahamonitor.newui E/SDL﹕ onWindowFocusChanged(): true
10-05 15:28:41.814    9118-9118/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ export_player_get_aspect_ratio_sizes1: 1, 0, 0, 720, 1134
10-05 15:28:41.814    9118-9118/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ export_player_get_aspect_ratio_sizes2: 1, 0, 0, 720, 1134
10-05 15:28:42.925    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/file_content_provider.c﹕ avformat_open_input: max_picture_buffer 3041280, raw_packet_buffer_remaining_size 2500000
10-05 15:28:45.164    9118-9318/com.ims.mid.android.sahamonitor.newui I/System.out﹕ DELAY : 10000
10-05 15:28:45.506    9118-9318/com.ims.mid.android.sahamonitor.newui I/System.out﹕ [ 10-05 15:28:45.506  9118: 9318 I/System.out ]
10-05 15:28:45.506    9118-9318/com.ims.mid.android.sahamonitor.newui I/System.out﹕ <ims><Alm><aNm>Motion Detected</aNm><iAT>2016-10-05 15:17:14.0</iAT><dNm>Motion sensor</dNm><tDf>11</tDf></Alm><Alm><aNm>Motion Detected</aNm><iAT>2016-10-05 15:10:17.0</iAT><dNm>Motion sensor</dNm><tDf>18</tDf></Alm><Alm><aNm>Panic Situation</aNm><iAT>2016-10-05 15:01:12.0</iAT><dNm>Mini-mote</dNm><tDf>27</tDf></Alm><Alm><aNm>Panic Situation</aNm><iAT>2016-10-05 15:01:10.0</iAT><dNm>Mini-mote</dNm><tDf>27</tDf></Alm><Alm><aNm>Panic Situation</aNm><iAT>2016-10-05 15:01:05.0</iAT><dNm>Mini-mote</dNm><tDf>27</tDf></Alm><Alm><aNm>Panic Situation</aNm><iAT>2016-10-05 15:00:32.0</iAT><dNm>Mini-mote</dNm><tDf>28</tDf></Alm><Alm><aNm>Motion Detected</aNm><iAT>2016-10-05 14:56:27.0</iAT><dNm>Motion sensor</dNm><tDf>32</tDf></Alm><Alm><aNm>Image Uploaded</aNm><iAT>2016-10-05 14:55:35.0</iAT><dNm>PT camera</dNm><tDf>33</tDf></Alm><Alm><aNm>Door Open</aNm><iAT>2016-10-05 14:55:22.0</iAT><dNm>Conference Room Door</dNm><tDf>33</tDf></Alm><Alm><aNm>Motion Detected</aNm><iAT>2016-10-05 14:52:38.0</iAT><dNm>Motion sensor</dNm><tDf>36</tDf></Alm></ims>
10-05 15:28:46.146    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/file_content_provider.c﹕ stream [0] stream_type:0 codec_type:28()
10-05 15:28:46.146    9118-9563/com.ims.mid.android.sahamonitor.newui E/jni/src/content/file_content_provider.c﹕ file_cp_open: VIDEO INFO  width 320, height 240, pix_fmt 12, profile 66, level 13, bit_rate 0, time_base.num 1, time_base.den 30, Codec ID 28(H264:28), extra 96, 0.1
10-05 15:28:46.171    9118-9562/com.ims.mid.android.sahamonitor.newui E/MediaPlayerTest﹕ Form Native Player status: 102
10-05 15:28:46.171    9118-9562/com.ims.mid.android.sahamonitor.newui E/MediaPlayerTest﹕ Form Native Player status: 1
10-05 15:28:46.171    9118-9562/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ player_open: Video renderer thread init: synchro 1
10-05 15:28:46.219    9118-9562/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ player_open: Video renderer thread start.
10-05 15:28:46.221    9118-9788/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Android_JNI_SetupThread
10-05 15:28:46.226    9118-9788/com.ims.mid.android.sahamonitor.newui E/jni/src/renderer/video_renderer_thread.c﹕ video_renderer_thread: Renderer provider init
10-05 15:28:46.226    9118-9788/com.ims.mid.android.sahamonitor.newui E/MediaPlayerTest﹕ Form Native Player status: 302
10-05 15:28:46.227    9118-9118/com.ims.mid.android.sahamonitor.newui I/System.out﹕ player error3 :
10-05 15:28:46.227    9118-9118/com.ims.mid.android.sahamonitor.newui I/System.out﹕ player error4 :
10-05 15:28:46.227    9118-9788/com.ims.mid.android.sahamonitor.newui E/jni/src/renderer/video_renderer_thread.c﹕ video_renderer_thread: Renderer provider open: 2
10-05 15:28:46.227    9118-9788/com.ims.mid.android.sahamonitor.newui E/jni/src/renderer/video_renderer_thread.c﹕ video_renderer_thread: Processor provider init: 0
10-05 15:28:46.239    9118-9562/com.ims.mid.android.sahamonitor.newui E/jni/src/player.c﹕ player_open: Video decoder thread start.
10-05 15:28:46.241    9118-9789/com.ims.mid.android.sahamonitor.newui E/SDL﹕ Android_JNI_SetupThread
10-05 15:28:46.241    9118-9789/com.ims.mid.android.sahamonitor.newui E/jni/src/decoder/video_decoder_provider.c﹕ =>vdp_init
10-05 15:28:46.241    9118-9789/com.ims.mid.android.sahamonitor.newui E/jni/src/decoder/omxil_video_decoder_provider.c﹕ omxil_vdp_open started
10-05 15:28:46.323    9118-9789/com.ims.mid.android.sahamonitor.newui W/VideoCapabilities﹕ Unrecognized profile 2130706433 for video/avc
10-05 15:28:46.339    9118-9789/com.ims.mid.android.sahamonitor.newui W/AudioCapabilities﹕ Unsupported mime audio/amr-wb-plus
10-05 15:28:46.345    9118-9789/com.ims.mid.android.sahamonitor.newui W/VideoCapabilities﹕ Unsupported mime video/mpeg2
10-05 15:28:46.374    9118-9789/com.ims.mid.android.sahamonitor.newui I/VideoCapabilities﹕ Unsupported profile 4 for video/mp4v-es
10-05 15:28:46.389    9118-9789/com.ims.mid.android.sahamonitor.newui E/jni/src/decoder/omxil_video_decoder_provider.c﹕ omxil_vdp_open: Number of profile levels: 0
10-05 15:28:46.522    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI CallObjectMethod called with pending exception 'java.lang.IllegalArgumentException' thrown in unknown throw location
10-05 15:28:46.522    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]     in call to CallObjectMethod
10-05 15:28:46.522    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65] "SDL_thread" prio=5 tid=31 Runnable
10-05 15:28:46.522    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12fd50a0 self=0xb8c6d600
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   | sysTid=9789 nice=0 cgrp=apps sched=0/0 handle=0xb8d0f6e8
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=3 stm=2 core=0 HZ=100
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   | stack=0x9c80e000-0x9c810000 stackSize=1012KB
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #00 pc 00004f60  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext_)+23)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #01 pc 00003665  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext_)+8)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #02 pc 00256ad1  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const_, art::mirror::ArtMethod_)+84)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #03 pc 00239687  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+158)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #04 pc 000b1a2b  /system/lib/libart.so (art::JniAbort(char const_, char const_)+610)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #05 pc 000b2165  /system/lib/libart.so (art::JniAbortF(char const_, char const_, ...)+68)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #06 pc 000b541f  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv_, int, char const_)+1346)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #07 pc 000ba1b1  /system/lib/libart.so (art::CheckJNI::CallObjectMethod(_JNIEnv_, _jobject_, _jmethodID_, ...)+48)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #08 pc 000b82e1  /data/app/com.ims.mid.android.sahamonitor.newui-2/lib/arm/librtspplr-armeabi-v7a.so (omxil_vdp_open+2032)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #09 pc 000b4cd5  /data/app/com.ims.mid.android.sahamonitor.newui-2/lib/arm/librtspplr-armeabi-v7a.so (vdp_open+188)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #10 pc 000b52f9  /data/app/com.ims.mid.android.sahamonitor.newui-2/lib/arm/librtspplr-armeabi-v7a.so (video_decoder_thread_method+516)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #11 pc 000ab899  /data/app/com.ims.mid.android.sahamonitor.newui-2/lib/arm/libSDL2-armeabi-v7a.so (SDL_RunThread+72)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #12 pc 000ac0ed  /data/app/com.ims.mid.android.sahamonitor.newui-2/lib/arm/libSDL2-armeabi-v7a.so (???)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #13 pc 00016813  /system/lib/libc.so (__pthread_start(void_)+30)
10-05 15:28:46.523    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   native: #14 pc 00014723  /system/lib/libc.so (__start_thread+6)
10-05 15:28:46.524    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]   (no managed stack frames)
10-05 15:28:46.524    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/check_jni.cc:65]
10-05 15:28:47.263    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/runtime.cc:314] Runtime aborting...
10-05 15:28:47.263    9118-9789/com.ims.mid.android.sahamonitor.newui A/art﹕ art/runtime/runtime.cc:314] Aborting thread:

**Comment by VideoExpertsGroup1** [comment]
Hi naveen1988,

Please use the latest libs from here https://github.com/VideoExpertsGroup/MediaPlayerSDK/tree/master/libs

Regards,
Video Experts Group
